[tool.poetry]
name = "ambiente-virutal"
version = "0.1.0"
description = ""
authors = ["otonielnn <otoniel_2002@live.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
